name: Manifest Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  manifest-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check manifest.json exists
      run: |
        if [ ! -f manifest.json ]; then
          echo "manifest.json not found!"
          exit 1
        fi
        echo "manifest.json found"
    
    - name: Validate JSON syntax
      run: |
        python -c "import json; json.load(open('manifest.json'))"
        echo "manifest.json is valid JSON"
