name: Prospector Python Static Analysis

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  prospector:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install prospector[with_pyroma]
    
    - name: Run Prospector
      run: prospector --zero-exit main.py
    
    - name: Upload Prospector report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: prospector-report
        path: prospector-report.json
